In [4]:
!ls cpm_2_0_tf_encoder

assets	keras_metadata.pb  saved_model.pb  variables


In [8]:
import tensorflow as tf
import tensorflow_hub as hub

In [6]:
model = hub.load('cpm_2_0_tf_encoder')

In [9]:
out = model(tf.constant([[5503, 145, 44, 44]]))

In [16]:
out['last_hidden_state'][0, 0, :10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.5349307 ,  0.07466483,  0.00511227,  0.18260963,  0.0014073 ,
        0.02666289, -0.03043771, -0.01867431, -0.09950671, -0.16626428],
      dtype=float32)>

In [17]:
out['last_hidden_state'][0, 1, :10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.00619042, -0.01400952, -0.03173273,  0.04004718, -0.0037609 ,
       -0.04000187, -0.01914766,  0.02522734,  0.04495345, -0.01402467],
      dtype=float32)>

In [18]:
out['last_hidden_state'][0, 2, :10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.9101447e-01,  3.8479471e-01, -8.0627367e-02,  3.5968775e-04,
       -6.1262432e-02, -9.2271268e-02, -9.8565049e-02, -1.6662593e-01,
       -1.5626278e-02, -2.1819761e-01], dtype=float32)>